### PR TITLE
Remove phantom.js fixture

### PR DESCRIPTION
**Pull request by jugmac00**
The fixture was introduced for the Landscape project, but Landscape does not use this project any more.

If you rely on this feature, please reach out on the GitHub tracker of this project and then discuss whether and how this fixture could be included again.

Also see #19.

This removes the last but one test failure when running the tests with an older version of Twisted.

### CODE REVIEW

**Review by jelmer — APPROVED** [review]

**Comment by jugmac00** [comment]
I do not have permissions to merge myself. Given that I am already an owner on PyPI for this package, maybe someone could grant me permissions for the GitHub project, too? Colin knows me personally, and I interacted with Jelmer occasionally on Launchpad and on mailinglists. Thank you!

**Comment by jelmer** [comment]
Yeah, we should just add you. Let me merge this and work out if I can do the project membership thing.

**Comment by jelmer** [comment]
It doesn't look like I can add you to the project, we'll need either @rbtcollins or @jml to do that.

**Comment by jugmac00** [comment]
re-pinging @rbtcollins and @jml Could you please make me an admin for this project? Which as outline above, is probably only used by my team at all? Thank you.

**Comment by jugmac00** [comment]
Maybe also @freeekanayaka could grant me admin permissions for this repository.

**Comment by freeekanayaka** [comment]
> Maybe also @freeekanayaka could grant me admin permissions for this repository.

I'm afraid I don't have admin privileges on this repo.

**Comment by jml** [comment]
@jelmer I have granted you admin permissions.

**Pull request merged**
